// One-time dev script: vendor Google Fonts locally as woff2 so the PWA works
// fully offline with no third-party request. Run: node tools/fetch-fonts.mjs
// Output: /fonts/*.woff2 and /fonts/fonts.css (relative url() paths).
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const CHROME_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

// Match the families OnTime already uses, so the look is unchanged:
// Fraunces (display serif) + Quicksand (rounded UI face).
const QUERY =
  'family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700' +
  '&family=Quicksand:wght@400;500;600;700&display=swap';

const cssUrl = `https://fonts.googleapis.com/css2?${QUERY}`;
const res = await fetch(cssUrl, { headers: { 'User-Agent': CHROME_UA } });
const css = await res.text();
if (!/woff2/.test(css)) {
  console.error('Expected woff2 URLs but got:\n', css.slice(0, 400));
  process.exit(1);
}

await mkdir(join(root, 'fonts'), { recursive: true });

// Google emits one @font-face per unicode-range subset; keep only `latin`.
const blocks = css.split('@font-face').slice(1);
const faces = [];
for (const block of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([0-9]+)/.exec(block)?.[1];
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
  if (!family || !weight || !url || !range) continue;
  if (!/^U\+0000/i.test(range) && !/^U\+0+(-|,|$)/i.test(range)) continue; // latin only
  const slug = `${family.toLowerCase()}-${weight}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': CHROME_UA } })).arrayBuffer());
  await writeFile(join(root, 'fonts', slug), buf);
  faces.push({ family, weight, slug, range, size: buf.length });
  console.log(`saved fonts/${slug} (${(buf.length / 1024).toFixed(1)} KB)`);
}

const out = [
  '/* Auto-generated by tools/fetch-fonts.mjs — vendored for offline use. */',
  ...faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url(./${f.slug}) format('woff2');
  unicode-range: ${f.range};
}`),
].join('\n');
await writeFile(join(root, 'fonts', 'fonts.css'), out + '\n');
console.log(`\nWrote fonts/fonts.css with ${faces.length} faces.`);
